apiVersion: v1
kind: Pod
metadata:
  name: chatapp
  namespace: chatapp-namespace
  labels:
     app: chatapp
spec:
  containers:
  - name: chatapp
    image: sayalikokane5/chatapp:1.0
    ports:
    - containerPort: 8080
